language: python

python:	
 - "3.7.0"	

cache: pip	

install:	
 - pip install -r requirements.txt
 - pip install codeclimate-test-reporter

script:	
 
 - pytest --cov=app/
 - coveralls
 
after_success:
 - coveralls
 - codeclimate-test-reporter