language: python

python:	
 - "3.7-dev"	

cache: pip	

install:	
 - pip install -r requirements.txt
 - pip install codeclimate-test-reporter

script:	
 
 - pytest --cov-report term-missing --cov=app 
 - coveralls
 
after_success:
 - coveralls
 - codeclimate-test-reporter