language: python

python:	
 - "3.7-dev"	

cache: pip	

install:	
 - pip install -r requirements.txt
 - pip install codeclimate-test-reporter

script:	
 
 -  python -m pytest --cov=app
 - coveralls
 
after_success:
 - coveralls
 - codeclimate-test-reporter